@server=http://localhost:8080
@username=admin
@password=admin


### Type
# @name Type_GET
GET {{server}}/odata/v4/TypeService/Type
Authorization: Basic {{username}}:{{password}}


### Type
# @name Type_POST
POST {{server}}/odata/v4/TypeService/Type
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "f3c2701d-b214-4eec-bb0e-1f4d8b41a779",
  "name": "Consulting",
  "createdAt": "2023-01-01T00:00:00.000Z",
  "createdBy": "createdBy.type@example.org",
  "modifiedAt": "2023-01-02T00:00:00.000Z",
  "modifiedBy": "modifiedBy.type@example.org",
  "IsActiveEntity": true
}


### Type
# @name Type_PATCH
PATCH {{server}}/odata/v4/TypeService/Type(ID=f3c2701d-b214-4eec-bb0e-1f4d8b41a779,IsActiveEntity=true)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "f3c2701d-b214-4eec-bb0e-1f4d8b41a779",
  "name": "Updated Consulting",
  "createdAt": "2023-01-01T00:00:00.000Z",
  "createdBy": "createdBy.type@example.org",
  "modifiedAt": "2023-01-03T00:00:00.000Z",
  "modifiedBy": "modifiedBy.type@example.org"
}


### Type
# @name Type_DELETE
DELETE {{server}}/odata/v4/TypeService/Type(ID=f3c2701d-b214-4eec-bb0e-1f4d8b41a779,IsActiveEntity=true)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### User
# @name User_GET
GET {{server}}/odata/v4/TypeService/User
Authorization: Basic {{username}}:{{password}}
