
---
spring:
  config.activate.on-profile: default
  sql.init.platform: h2
cds:
  data-source.auto-config.enabled: false
  security:
    authentication:
      normalize-provider-tenant: true
    mock:
      enabled: true
      users:
        admin:
          password: admin
          roles:
            -ProjectManager
            -Administrator
---
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true
