
---
spring:
  config.activate.on-profile: default
  sql.init.platform: h2
  sql.init.schema-locations: classpath:schema-h2.sql
cds:
  data-source.auto-config.enabled: false
  odata-v4.endpoint.path: "/odata/v4"
  security:
    authentication:
      normalize-provider-tenant: true
    mock:
      enabled: true
      users:
        admin:
          password: admin
          roles:
            - ProjectManager
            - Administrator
---
management:
  endpoint:
    health:
      show-components: always
      probes.enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults.enabled: false
    ping.enabled: true
    db.enabled: true
